from pathlib import Path

p=Path('ERP-INTEGRAL-4.0-SUPABASE-MIGRADO/public/app.js')
s=p.read_text()

repls=[
("const USER_TYPES=['Administrador','Comercial','Financeiro','Projetos','Topografia','Marketing','Pós-protocolo','Atendimentos','Diretor Técnico'];",
 "const USER_TYPES=['Administrador','Comercial','Financeiro','Diretor Financeiro','Diretor de Projetos','Projetos','Topografia','Jurídico','Marketing','Pós-protocolo','Atendimentos','Diretor Técnico'];"),
("const USER_SECTORS=['Administrativo','Comercial','Financeiro','Projetos','Topografia','Marketing','Pós-protocolo','Atendimentos'];",
 "const USER_SECTORS=['Administrativo','Comercial','Financeiro','Projetos','Topografia','Jurídico','Marketing','Pós-protocolo','Atendimentos'];"),
("const METAS_SECTORS=['Projetos','Topografia','Pós-protocolo','Atendimentos'];",
 "const METAS_SECTORS=['Projetos','Topografia','Pós-protocolo','Jurídico'];"),
("function isTechDirector(){return currentUser?.type==='Diretor Técnico';}\nfunction isMetasManager(){return isAdmin()||isTechDirector();}\nfunction canSeePlan(plan){return canManageCore()||isTechDirector()||plan.steps.some(s=>s.responsibleIds.includes(currentUser.id));}\nfunction canEditStep(step){return isAdmin()||isTechDirector()||step.responsibleIds.includes(currentUser.id);}\nfunction isMetasSector(){return METAS_SECTORS.includes(currentUser?.type);}\nfunction canSeeMetas(){return isMetasManager()||isMetasSector();}",
 "function isTechDirector(){return currentUser?.type==='Diretor Técnico';}\nfunction accessNorm(v){return String(v||'').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().trim();}\nfunction userMatchesAccess(...names){const keys=names.map(accessNorm);return keys.includes(accessNorm(currentUser?.type))||keys.includes(accessNorm(currentUser?.sector));}\nfunction isProjectDirector(){return userMatchesAccess('Diretor de Projetos','Diretor de Projeto');}\nfunction isFinanceAccess(){return userMatchesAccess('Financeiro','Diretor Financeiro');}\nfunction isRestrictedOperational(){return userMatchesAccess('Topografia','Projetos','Pós-protocolo','Pós Protocolo','Jurídico','Juridico');}\nfunction canViewProjects(){return isAdmin()||isComercial()||isProjectDirector()||isFinanceAccess();}\nfunction isMetasManager(){return isAdmin()||isTechDirector()||isProjectDirector();}\nfunction canSeePlan(plan){return canManageCore()||isTechDirector()||isProjectDirector()||isFinanceAccess()||plan.steps.some(s=>s.responsibleIds.includes(currentUser.id));}\nfunction canEditStep(step){return isAdmin()||isTechDirector()||isProjectDirector()||step.responsibleIds.includes(currentUser.id);}\nfunction isMetasSector(){return isRestrictedOperational();}\nfunction canSeeMetas(){return isMetasManager()||isFinanceAccess()||isMetasSector();}"),
("function navItems(){if(isAdmin())return ADMIN_NAV;if(isComercial())return COMERCIAL_NAV;if(isTechDirector())return [['metas','Metas']];if(isMetasSector())return [['plans','Planos de trabalho'],['metas','Metas']];return [['plans','Planos de trabalho']];}",
 "function navItems(){\n  if(isAdmin())return ADMIN_NAV;\n  if(isProjectDirector()||isFinanceAccess())return [['projects','Projetos'],['plans','Planos de trabalho'],['metas','Metas']];\n  if(isRestrictedOperational())return [['plans','Planos de trabalho'],['metas','Metas']];\n  if(isComercial())return COMERCIAL_NAV;\n  if(isTechDirector())return [['metas','Metas']];\n  return [['plans','Planos de trabalho']];\n}"),
("<div class=\"toolbar\"><div class=\"left\"><input id=\"searchProjects\" class=\"search\" placeholder=\"Pesquisar projeto, cliente, tipo ou responsável\" value=\"${esc(searchTerm)}\"></div><div class=\"right\"><button id=\"newProject\" class=\"btn\">Adicionar projeto</button></div></div>",
 "<div class=\"toolbar\"><div class=\"left\"><input id=\"searchProjects\" class=\"search\" placeholder=\"Pesquisar projeto, cliente, tipo ou responsável\" value=\"${esc(searchTerm)}\"></div><div class=\"right\">${canManageCore()?'<button id=\"newProject\" class=\"btn\">Adicionar projeto</button>':''}</div></div>"),
("<td class=\"actions\"><button class=\"btn icon secondary\" data-edit-project=\"${p.id}\" title=\"Editar\">✎</button><button class=\"btn icon danger\" data-del-project=\"${p.id}\" title=\"Excluir\">×</button></td>",
 "<td class=\"actions\">${canManageCore()?`<button class=\"btn icon secondary\" data-edit-project=\"${p.id}\" title=\"Editar\">✎</button><button class=\"btn icon danger\" data-del-project=\"${p.id}\" title=\"Excluir\">×</button>`:''}</td>"),
("  $('#newProject').onclick=()=>projectModal();\n  $$('[data-open-project]').forEach(b=>b.onclick=()=>{currentProjectId=b.dataset.openProject;renderProjects()});\n  $$('[data-edit-project]').forEach(b=>b.onclick=()=>projectModal(findProject(b.dataset.editProject)));\n  $$('[data-del-project]').forEach(b=>b.onclick=()=>deleteProject(b.dataset.delProject));",
 "  if(canManageCore())$('#newProject')?.addEventListener('click',()=>projectModal());\n  $$('[data-open-project]').forEach(b=>b.onclick=()=>{currentProjectId=b.dataset.openProject;renderProjects()});\n  if(canManageCore()){\n    $$('[data-edit-project]').forEach(b=>b.onclick=()=>projectModal(findProject(b.dataset.editProject)));\n    $$('[data-del-project]').forEach(b=>b.onclick=()=>deleteProject(b.dataset.delProject));\n  }"),
("<div class=\"toolbar project-detail-toolbar\"><button id=\"backProjects\" class=\"btn ghost\">← Voltar</button><div class=\"right\"><button id=\"editProjectDetail\" class=\"btn icon secondary\" title=\"Editar projeto\">✎</button><button id=\"delProjectDetail\" class=\"btn icon danger\" title=\"Excluir projeto\">×</button></div></div>",
 "<div class=\"toolbar project-detail-toolbar\"><button id=\"backProjects\" class=\"btn ghost\">← Voltar</button><div class=\"right\">${canManageCore()?'<button id=\"editProjectDetail\" class=\"btn icon secondary\" title=\"Editar projeto\">✎</button><button id=\"delProjectDetail\" class=\"btn icon danger\" title=\"Excluir projeto\">×</button>':''}</div></div>"),
("<div class=\"section-head\"><div><h4>Etapas do projeto</h4><span class=\"muted\">${p.stages.length} etapa(s)</span></div><button id=\"addProjectStage\" class=\"btn icon secondary\" title=\"Adicionar etapa\">＋</button></div>",
 "<div class=\"section-head\"><div><h4>Etapas do projeto</h4><span class=\"muted\">${p.stages.length} etapa(s)</span></div>${canManageCore()?'<button id=\"addProjectStage\" class=\"btn icon secondary\" title=\"Adicionar etapa\">＋</button>':''}</div>"),
("<div class=\"actions stage-buttons\"><button class=\"btn icon secondary\" data-edit-stage=\"${s.id}\" title=\"Editar\">✎</button><button class=\"btn icon danger\" data-del-stage=\"${s.id}\" title=\"Excluir\">×</button></div>",
 "${canManageCore()?`<div class=\"actions stage-buttons\"><button class=\"btn icon secondary\" data-edit-stage=\"${s.id}\" title=\"Editar\">✎</button><button class=\"btn icon danger\" data-del-stage=\"${s.id}\" title=\"Excluir\">×</button></div>`:''}"),
("  $('#backProjects').onclick=()=>{currentProjectId=null;renderProjects()};\n  $('#editProjectDetail').onclick=()=>projectModal(p);$('#delProjectDetail').onclick=()=>deleteProject(p.id);$('#addProjectStage').onclick=()=>stageModal(p);",
 "  $('#backProjects').onclick=()=>{currentProjectId=null;renderProjects()};\n  if(canManageCore()){\n    $('#editProjectDetail')?.addEventListener('click',()=>projectModal(p));\n    $('#delProjectDetail')?.addEventListener('click',()=>deleteProject(p.id));\n    $('#addProjectStage')?.addEventListener('click',()=>stageModal(p));\n  }"),
("  $$('[data-edit-stage]').forEach(b=>b.onclick=()=>stageModal(p,p.stages.find(x=>x.id===b.dataset.editStage)));\n  $$('[data-del-stage]').forEach(b=>b.onclick=()=>{if(confirm('Excluir etapa do projeto?')){p.stages=p.stages.filter(x=>x.id!==b.dataset.delStage);saveDB();renderProjectDetail()}});",
 "  if(canManageCore()){\n    $$('[data-edit-stage]').forEach(b=>b.onclick=()=>stageModal(p,p.stages.find(x=>x.id===b.dataset.editStage)));\n    $$('[data-del-stage]').forEach(b=>b.onclick=()=>{if(confirm('Excluir etapa do projeto?')){p.stages=p.stages.filter(x=>x.id!==b.dataset.delStage);saveDB();renderProjectDetail()}});\n  }"),
("db.users.filter(u=>u.active&&!['Administrador','Diretor Técnico'].includes(u.type))",
 "db.users.filter(u=>u.active&&!['Administrador','Diretor Técnico','Diretor de Projetos','Diretor Financeiro'].includes(u.type))"),
]

for old,new in repls:
    if old not in s:
        raise SystemExit(f'Trecho não encontrado para substituição:\n{old[:180]}')
    s=s.replace(old,new,1)

p.write_text(s)
