begin;
create or replace view public.erp_prazos with (security_invoker=true) as
 select 'meta:'||m.id chave,'meta'::text entidade_tipo,m.id entidade_id,m.titulo,coalesce(m.semana_inicio,m.created_at::date) inicio,m.prazo fim,coalesce(array(select r.usuario_id from public.meta_responsaveis r where r.meta_id=m.id),'{}') participantes from public.metas m where m.prazo is not null and m.status not in ('Concluído','Concluída','Cancelado','Cancelada')
 union all select 'plano:'||p.id,'plano',p.id,p.titulo,least(p.created_at::date,max(s.prazo)),max(s.prazo),coalesce(array(select distinct r.usuario_id from public.etapa_responsaveis r join public.etapas_plano z on z.id=r.etapa_id where z.plano_id=p.id),'{}') from public.planos_trabalho p join public.etapas_plano s on s.plano_id=p.id where p.status not in ('Concluído','Cancelado') group by p.id having max(s.prazo) is not null
 union all select 'etapa:'||s.id,'plano',p.id,p.titulo||' — '||s.titulo,least(s.created_at::date,s.prazo),s.prazo,coalesce(array(select r.usuario_id from public.etapa_responsaveis r where r.etapa_id=s.id),'{}') from public.etapas_plano s join public.planos_trabalho p on p.id=s.plano_id where s.prazo is not null and s.status not in ('Concluída','Concluído','Cancelado') and p.status not in ('Concluído','Cancelado')
 union all select 'processo:'||p.id,'processo',p.id,p.nucleo,least(p.etapa_iniciada_em::date,p.prazo),p.prazo,array[p.responsavel_id] from public.processos_kanban p where p.prazo is not null and p.ativo and not p.excluido_erp and p.etapa_atual not in ('Concluído','Concluída','Finalizado','Cancelado');
create or replace function public.erp_collab_action(op text,p jsonb) returns jsonb language plpgsql security invoker set search_path='' as $$begin if op='remover_pessoal' then delete from public.erp_agenda_pessoal where usuario_id=auth.uid() and chave=left(p->>'chave',300);return jsonb_build_object('id',null);end if;if op in ('evento','conversa') and nullif(p->>'entidade_tipo','') is not null and not erp_collab_private.entity_visible(p->>'entidade_tipo',(p->>'entidade_id')::uuid) then raise exception 'Você não tem acesso ao registro associado';end if;return erp_collab_private.mutate(op,p);end $$;
create or replace function public.erp_collab_notifications() returns table(chave text,titulo text,tipo text,entidade_tipo text,entidade_id uuid,evento_id uuid,conversa_id uuid,prazo date,lida boolean) language sql stable security invoker set search_path='' as $$ with d as (select (now() at time zone 'America/Sao_Paulo')::date dia),feed(chave,titulo,tipo,entidade_tipo,entidade_id,evento_id,conversa_id,prazo) as (select 'vinculo:'||p.chave,'Você está vinculado: '||p.titulo,'vinculo'::text,p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_prazos p where auth.uid()=any(p.participantes) union all select 'prazo:'||p.chave||':'||d.dia,case when p.fim<d.dia then 'Em atraso: ' else 'Prazo em '||(p.fim-d.dia)||' dia(s): ' end||p.titulo,'prazo',p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_prazos p cross join d where auth.uid()=any(p.participantes) and (p.fim-d.dia in (3,1) or p.fim<d.dia) union all select 'projeto_prazo:'||p.id||':'||d.dia,case when p.prazo_final<d.dia then 'Projeto em atraso: ' else 'Projeto vence em '||(p.prazo_final-d.dia)||' dia(s): ' end||p.nome,'prazo','projeto',p.id,null::uuid,null::uuid,p.prazo_final from public.projetos p cross join d where p.created_by=auth.uid() and p.prazo_final is not null and p.status not in ('Concluído','Cancelado') and (p.prazo_final-d.dia in (3,1) or p.prazo_final<d.dia) union all select 'evento:'||e.id,'Convite: '||e.titulo,'evento',e.entidade_tipo,e.entidade_id,e.id,null::uuid,(e.fim at time zone 'America/Sao_Paulo')::date from public.erp_eventos e where auth.uid()=any(e.participantes) and e.created_by<>auth.uid() and e.status='ativo' and e.fim>=now() union all select 'grupo:'||c.id,'Você foi incluído no grupo: '||c.titulo,'grupo',c.entidade_tipo,c.entidade_id,null::uuid,c.id,null::date from public.erp_conversas c where c.tipo='grupo' and c.created_by<>auth.uid() union all select 'mensagem:'||m.id,'Mensagem: '||c.titulo,'mensagem',c.entidade_tipo,c.entidade_id,m.evento_id,c.id,null::date from public.erp_mensagens m join public.erp_conversas c on c.id=m.conversa_id where m.autor_id<>auth.uid() and m.created_at>now()-interval '30 days' union all select 'exclusao:'||r.id,'Solicitação de exclusão de chat','exclusao',null,null::uuid,null::uuid,r.conversa_id,null::date from public.erp_exclusoes_chat r where r.status='pendente' and public.is_admin()) select f.*,exists(select 1 from public.erp_notificacoes_lidas l where l.usuario_id=auth.uid() and l.chave=f.chave) from feed f where erp_collab_private.active_user();$$;
revoke all on function public.erp_collab_action(text,jsonb),public.erp_collab_notifications() from public,anon;grant execute on function public.erp_collab_action(text,jsonb),public.erp_collab_notifications() to authenticated;
commit;

