create or replace function public.erp_collab_notifications() returns table(chave text,titulo text,tipo text,entidade_tipo text,entidade_id uuid,evento_id uuid,conversa_id uuid,prazo date,lida boolean) language sql stable security invoker set search_path='' as $$
 with d as (select (now() at time zone 'America/Sao_Paulo')::date dia), feed(chave,titulo,tipo,entidade_tipo,entidade_id,evento_id,conversa_id,prazo) as (
  select 'vinculo:'||p.chave,'Você está vinculado: '||p.titulo,'vinculo'::text,p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_prazos p where auth.uid()=any(p.participantes)
  union all select 'acompanhamento:'||p.chave,'Acompanhamento adicionado: '||p.titulo,'vinculo'::text,p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_agenda_pessoal a join public.erp_prazos p on p.chave=a.chave where a.usuario_id=auth.uid() and not auth.uid()=any(p.participantes)
  union all select 'prazo:'||p.chave||':'||d.dia,case when p.fim<d.dia then 'Em atraso: ' else 'Prazo em '||(p.fim-d.dia)||' dia(s): ' end||p.titulo,'prazo',p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_prazos p cross join d where auth.uid()=any(p.participantes) and (p.fim-d.dia in (3,1) or p.fim<d.dia)
  union all select 'prazo_pessoal:'||p.chave||':'||d.dia,case when p.fim<d.dia then 'Em atraso: ' else 'Prazo em '||(p.fim-d.dia)||' dia(s): ' end||p.titulo,'prazo',p.entidade_tipo,p.entidade_id,null::uuid,null::uuid,p.fim from public.erp_agenda_pessoal a join public.erp_prazos p on p.chave=a.chave cross join d where a.usuario_id=auth.uid() and not auth.uid()=any(p.participantes) and (p.fim-d.dia in (3,1) or p.fim<d.dia)
  union all select 'projeto_prazo:'||p.id||':'||d.dia,case when p.prazo_final<d.dia then 'Projeto em atraso: ' else 'Projeto vence em '||(p.prazo_final-d.dia)||' dia(s): ' end||p.nome,'prazo','projeto',p.id,null::uuid,null::uuid,p.prazo_final from public.projetos p cross join d where p.created_by=auth.uid() and p.prazo_final is not null and p.status not in ('Concluído','Cancelado') and (p.prazo_final-d.dia in (3,1) or p.prazo_final<d.dia)
  union all select 'evento:'||e.id,'Convite: '||e.titulo,'evento',e.entidade_tipo,e.entidade_id,e.id,null::uuid,(e.fim at time zone 'America/Sao_Paulo')::date from public.erp_eventos e where auth.uid()=any(e.participantes) and e.created_by<>auth.uid() and e.status='ativo' and e.fim>=now()
  union all select 'grupo:'||c.id,'Você foi incluído no grupo: '||c.titulo,'grupo',c.entidade_tipo,c.entidade_id,null::uuid,c.id,null::date from public.erp_conversas c where c.tipo='grupo' and c.created_by<>auth.uid()
  union all select 'mensagem:'||m.id,'Mensagem: '||c.titulo,'mensagem',c.entidade_tipo,c.entidade_id,m.evento_id,c.id,null::date from public.erp_mensagens m join public.erp_conversas c on c.id=m.conversa_id where m.autor_id<>auth.uid() and m.created_at>now()-interval '30 days'
  union all select 'exclusao:'||r.id,'Solicitação de exclusão de chat','exclusao',null,null::uuid,null::uuid,r.conversa_id,null::date from public.erp_exclusoes_chat r where r.status='pendente' and public.is_admin()
 ) select f.*,exists(select 1 from public.erp_notificacoes_lidas l where l.usuario_id=auth.uid() and l.chave=f.chave) from feed f where erp_collab_private.active_user();
$$;